version: '3.8'

services:
  server1:
    image: nginx:alpine
    container_name: server20
    command: /bin/sh -c "echo 'Server 20' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"

  server2:
    image: nginx:alpine
    container_name: server21
    command: /bin/sh -c "echo 'Server 21' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"

  server3:
    image: nginx:alpine
    container_name: server22
    command: /bin/sh -c "echo 'Server 22' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"

  server4:
    image: nginx:alpine
    container_name: server23
    command: /bin/sh -c "echo 'Server 23' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"

  loadbalancer:
    image: nginx:alpine
    container_name: nginx-hash-base
    ports:
      - "8093:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
