version: '3.8'

services:
  server1:
    image: nginx:alpine
    container_name: server1
    command: /bin/sh -c "echo 'Server 1' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"

  server2:
    image: nginx:alpine
    container_name: server2
    command: /bin/sh -c "echo 'Server 2' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"

  server3:
    image: nginx:alpine
    container_name: server3
    command: /bin/sh -c "echo 'Server 3' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"

  nginx-lb:
    image: nginx:alpine
    container_name: nginx-lb
    ports:
      - "8080:8080"  # Round Robin
      - "8081:8081"  # Weighted RR
      - "8082:8082"  # Least Connections
      - "8083:8083"  # IP Hash
      - "8084:8084"  # Random
      - "8085:8085"  # Consistent Hash
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
